name: Design a simple workflow for dev enviroment to production

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
 DEV:
      # Type of runner  that the job will run on 
   run-on: ubuntu-latest
   environment: DEV
   
   Steps:
   
   #steps required for perform task include in a job 
   -uses: action.checkout/@v2
   
   -name: run a script
   run: |
   echo : "Im running job in dev environment"
   
   
   
    DEV:
      # Type of runner  that the job will run on 
   run-on: ubuntu-latest
   environment: DEV
   
   Steps:
   
   #steps required for perform task include in a job 
   -uses: action.checkout/@v2
   
   -name: run a script
   run: |
   echo : "Im running job in dev environment"
   
   
